### PR TITLE
1 feature 1 user management and login system

### LINKED ISSUE #1: [Feature 1] User Management and Login System
A user is able to create a username and password. User can login using their credentials.
Excluding view.

### PR DESCRIPTION
**Pull request by kunzhi-yu**
I implemented the use case for user login. I also updated the gitignore. 
Sincerely,
Alex Yu

### CODE REVIEW

**Review by sopleee — APPROVED** [review]
looks good, thanks!

**Review by projectavi — APPROVED** [review]
looks cool

**Review by mishaalkandapath — APPROVED** [review]
gitignore approved

**Review by rcordi — APPROVED** [review]
looks good!

**Pull request merged**
