### PR TITLE
6 feature 6 updatepaymentbalance and settlepayment use cases

### PR DESCRIPTION
**Pull request by rowanArora**
Removed PaymentInformation from the UpdatePaymentBalance use case constructor as it was completely unnecessary.

### CODE REVIEW

**Review by sopleee — APPROVED** [review]
these small fixes are important to maintaining clean architecture- make sure you later reflect these changes in the test

**Review by mishaalkandapath — APPROVED** [review]
Thank you for fixing ur minor errors that was important for compilation and functionality

**Review by rcordi — APPROVED** [review]
Groovy! implementing these smalls changes enables our application to handle more exceptions. However, please remove the Data Structure PaymentInformation from the constructor of UpdatePaymentBalance since it violates clean architecture and prevents the initialization of UpdatePaymentBalanceController in the view.

**Comment by mishaalkandapath** [comment]
Pull request close due to duplicate changes that were made in the small changes branch

**Pull request closed without merging**
