### PR TITLE
added json-simple libraries with other minor setup in data access classes

### PR DESCRIPTION
**Pull request by sopleee**

### CODE REVIEW

**Review by projectavi — APPROVED** [review]
Thanks for adding the Json library for data persistence

**Review by kunzhi-yu — APPROVED** [review]
Hello, thanks for figuring out how to get the library for json. We can now set up the DataAccess layers.

**Comment by mishaalkandapath** [comment]
Setup for json-simple looks good. Initial setup for the user and groups json also looks good. 
Approved for the purpose of merging into other branch also working on another aspect of data storage.

**Review by mishaalkandapath — APPROVED** [review]
Setup for json-simple looks good. Initial setup for the user and groups json also looks good.
Approved for the purpose of merging into other branch also working on another aspect of data storage.

**Pull request merged**
