### PR TITLE
6 feature 6 updatepaymentbalance and settlepayment use cases

### LINKED ISSUE #6: [Feature 6]  UpdatePaymentBalance Use Case
Removes an item from the PlanningList
Updates the Debt and PurchaseBalance following changes during a purchase

Implement all the associated input output boundaries

### PR DESCRIPTION
**Pull request by rowanArora**
Hello everyone,

I believe I have completed most of my work for the project. Please take a look at it and leave any feedback. Thank you!

- Rowan

### CODE REVIEW

**Comment by mishaalkandapath** [comment]
Cannot pass User entity into output data structure in line 102. instead please dont add this (the username which is key can identify the user)
In general, you cannot pass entities into the view layer.

Additionally, divide the item price by the number of users in the purchase, and not the whole purchase

**Review by projectavi — CHANGES_REQUESTED** [review]
Some functions are missing javadocs, and the ones that have documentation dont follow the javadoc format convention, please update them to follow convention.
Need to catch the runtime exceptions and other exceptions to pass an error message back to user.
When subtracting the price incurred to participating users, the amount needs to be divided by the number of users involved in the purchase.

**Review by mishaalkandapath — CHANGES_REQUESTED** [review]
Cannot pass User entity into output data structure in line 102. instead please don't add this (the username which is key can identify the user)
In general, you cannot pass entities into the view layer.

Additionally, divide the item price by the number of users in the purchase, and not the whole purchase

**Review by mishaalkandapath — CHANGES_REQUESTED** [review]
Please add your javadocs

**Review by sopleee — CHANGES_REQUESTED** [review]
The way that we make purchases and update debts- as specified in our blueprint- is that you purchase an item and split it with a select number of users in the group. In your Controller, you are currently only passing in the user who makes the purchase, but you also need a reference to every user who is splitting on this purchase instead of assuming all users are splitting equally. 
In PaymentDetails- add a parameter to store a list of usernames of users that need to be split into the purchase (minus the one who bought)
In UpdatePaymentBalance, instead of mutating each debt that the user who bought is owing, you should loop in any debts involving both the user and a user who split on the purchase.

You shouldn't be implementing RemoveFromPlanningBoundaryIn, ToRemove, and RemoveFromPlanning- this file is from a use case we are deleting.

**Review by projectavi — COMMENTED** [review]
We need to resolve what is going on with the payment details data structure, putting this on the agenda for the team meeting tomorrow

**Review by mishaalkandapath — APPROVED** [review]
the required code changes have beenmade. Javadocs have been implemented, testintg has also been implemented. 
Well done!

**Review by projectavi — APPROVED** [review]
Hopefully works fingers crossed

**Review by sopleee — APPROVED** [review]
all these changes are now consistent with clean architecture, we have resolved overlap issues between SettlementPayment and this use case that caused error. Looks good to me!

**Pull request merged**
