### PR TITLE
Integrated AddPurchase with the database and implemented the presenter

### PR DESCRIPTION
**Pull request by projectavi**
Integrated the item and group databases and integrated user database assuming that it follows the same convention as the other two. Also updated the UpdatedLists data structure to store nested lists.

### CODE REVIEW

**Review by kunzhi-yu — CHANGES_REQUESTED** [review]
Please convert these comments to javadocs.

**Review by sopleee — CHANGES_REQUESTED** [review]
Please make your lines shorter so your code is more readable. From the example in class, your presenter should simply return the data structure instead of breaking it down

**Review by sopleee — CHANGES_REQUESTED** [review]
Please add return types to your execute method in your controller, input boundary, and use case

**Review by sopleee — APPROVED** [review]
Thanks for shortening the lines and adding return types. Your code follows clean architecture as before

**Review by sopleee — CHANGES_REQUESTED** [review]
in the UpdatedLists data structure, to account to failed views, I would make a prepareFailView function and a second constructor that takes in a string with the description of the error

**Review by sopleee — CHANGES_REQUESTED** [review]
I'd suggest just making a new constructor for the failed outcomes since failed outcomes do not have lists. Also, please add return information in your javadoc

**Review by sal3h-yas1in — APPROVED** [review]
Thank you for adding code documentation, all of it seems appropriate and the details are succinctly delivered. Good job :)

**Review by kunzhi-yu — APPROVED** [review]
Functionality looks good. You should consider breaking up executeUseCase in your AddPurchase use case into a helper method or two. Since you need comments to help other's understand your code, that probably indicated the single method is too complex. See refactoring guru for more info.

**Review by sopleee — CHANGES_REQUESTED** [review]
please change your runtime exceptions to failure messages for the view to avoid the program from crashing

**Review by sopleee — CHANGES_REQUESTED** [review]
extractUsers function throws an error that is not caught when this helper method is used on line 127 (in AddPurchase)

**Review by sopleee — APPROVED** [review]
thanks for handling the runtime error, looks all good now

**Pull request merged**
