### PR TITLE
wrote javadocs

### PR DESCRIPTION
**Pull request by sopleee**

### CODE REVIEW

**Review by mishaalkandapath — APPROVED** [review]
Documentation looks fine.

**Review by kunzhi-yu — APPROVED** [review]
Nice javadocs

**Review by projectavi — CHANGES_REQUESTED** [review]
Good documentation overall however please follow Java convention as Intellij constructs it and follow the format for describing parameters - i see you have done it in most places but functions like public ItemDataAccess(String testPath) does not have this. Please check once more.

**Review by projectavi — APPROVED** [review]
Good job on the javadocs and thanks for fixing convention issues. Approved and merging

**Pull request merged**
