### PR TITLE
updated group access classes to use code from parent class to avoid repetitive code, changed some naming

### LINKED ISSUE #15: [Feature 7] Implement Group Data Access Interface and Data Access
Create CSV files for Groups and Users to store all relevant data, set up access-points to retrieve proper entity objects (via userId and groupId)
Data Access Classes should implement the Data Access Interfaces

### PR DESCRIPTION
**Pull request by sopleee**

### CODE REVIEW

**Review by projectavi — APPROVED** [review]
Good job on reducing the duplication of code!

**Comment by mishaalkandapath** [comment]
reduced smelly code nice! accepting changes for group database functionality

**Review by mishaalkandapath — APPROVED** [review]
reduced smelly code nice! accepting changes for group database functionality

**Review by rcordi — APPROVED** [review]
Great job optimizing database implementation.

**Pull request merged**
