### PR TITLE
Completed userLogin, userRegister, File structure for testing

### PR DESCRIPTION
**Pull request by kunzhi-yu**
Completed the userLogin, userRegister use case and its associated classes (presenters, data structures).
Also created a file structure for people to being writing tests.

### CODE REVIEW

**Review by projectavi — CHANGES_REQUESTED** [review]
Good work on the use case and documentation. Requesting the creation and implementation of an output data structure for User login. This data structure needs to contain all of the information that the view needs for the user to use the program. This includes all of the information on all of the groups that the user is part of so that the home page and individual group pages can be set up and initialized by the view. Other than this, looks good.

**Comment by mishaalkandapath** [comment]
Resolved a merge conflict due to change of whitespace in Group.java. Please do not change files that do not belong to your usecase

**Review by mishaalkandapath — CHANGES_REQUESTED** [review]
Your code is highly incomplete:
1. Many getters in LoggedInInfo.java are not implemented.
2. Exceptions are not handled for user not exist or password mismatch
3. do not throw exceptions into the view layer, handle it yourself and pass it by wrapping it into your output ds (reference branch 3 use cases for details)
4. do not check if the username is available in the controller, that is probably a functionlity for your use case.
5. Please make sure your class entity constructors match up with those in the entity branch (branch 2, refer pull request)

**Comment by mishaalkandapath** [comment]
merge conflict resolved

**Review by mishaalkandapath — APPROVED** [review]
Thank you for making the requested changes. Accepting Pull request for now

**Review by sal3h-yas1in — APPROVED** [review]
Thank you for implementing this use case. We should focus next on writing thorough testing!

**Review by projectavi — CHANGES_REQUESTED** [review]
Data structure needs to return the users debt to the view for each group as well

**Review by projectavi — APPROVED** [review]
cool beans

**Pull request merged**
