### PR TITLE
changed the return type of the presenter

### PR DESCRIPTION
**Pull request by sopleee**

### CODE REVIEW

**Review by projectavi — CHANGES_REQUESTED** [review]
Good code, just please remove unused imports for cleanliness reasons! Thank you!

**Review by projectavi — APPROVED** [review]
Good job on fixing up your return types and cleaning up the code! Thank you!

**Review by kunzhi-yu — APPROVED** [review]
Looks good. You should show everyone else how to create HTML javadocs.

**Comment by mishaalkandapath** [comment]
resolved merge conflict that arose due to the generation of java docs

**Review by mishaalkandapath — CHANGES_REQUESTED** [review]
incorrect documentation in AddToPlanningbBoundaryOut
no java doc for AddToPlanning presenter

please fix documentation

**Review by projectavi — CHANGES_REQUESTED** [review]
Your presenter needs to implement both methods from the output boundary. 
When returning the purchased list, the internal lists order should be price then buyer not the other way around, we should consider switching to mappings later on.

**Review by projectavi — APPROVED** [review]
Approved. Thanks for making the necessary changes,

**Review by mishaalkandapath — APPROVED** [review]
Changes made. Well done!

**Pull request merged**
