### PR TITLE
Group Join and Group Create usecases

### LINKED ISSUE #3: [Feature 3] Group join, group create use cases
Allow a user to create new group.
Allow a user to join a group.

Implement all the associated input output boundaries

### PR DESCRIPTION
**Pull request by mishaalkandapath**
Implemented the Group join and Group create use cases with error handlers. Database integration is also complete, however, it is yet to be tested.

### CODE REVIEW

**Review by sopleee — CHANGES_REQUESTED** [review]
add helper methods in your use cases so that each method is shortened. each method should only do one thing. please add docstrings to your methods

**Review by projectavi — CHANGES_REQUESTED** [review]
Please add JavaDocs in the conventional format. The JoinedGroupInfo data structure should return all of the information that will be displayed on the group summary page such as the planning and purchased list and all of the items in it. This information is needed by the view to display the group. Other than that, the code is well commented and looks like it should run fine. Please make these two changes.

**Review by sopleee — APPROVED** [review]
everything looks good, thanks for breaking your method into helper methods and adding javadocs

**Review by projectavi — CHANGES_REQUESTED** [review]
Thank you for adding the information to the output data structure for the group join use case, one change is that we should keep the convention the same for how the lists are being returned to the view. Could you please change the storing of the planning and purchased lists to 2 dimensional lists with the id in the 0th position of the array and name in the 1st position. Extend this for the planning list to have the price and the buyer in the 2nd and 3rd positions in the internal lists. See AddPurchase.java's convertList function for details. Thank you.

**Comment by mishaalkandapath** [comment]
> Thank you for adding the information to the output data structure for the group join use case, one change is that we should keep the convention the same for how the lists are being returned to the view. Could you please change the storing of the planning and purchased lists to 2 dimensional lists with the id in the 0th position of the array and name in the 1st position. Extend this for the planning list to have the price and the buyer in the 2nd and 3rd positions in the internal lists. See AddPurchase.java's convertList function for details. Thank you.

sorry this cannot be changed. it is cleaner to represent the data structure in this way and is better code to do so. I understand that you may have implemented it with a non-standard list structure, but you will have to change that to abide by this.

However, for Milestone 4 I will follow this for ease of everybody else's implementation.

**Comment by projectavi** [comment]
Agreed a mapping is cleaner, post milestone 4 we can make this change universal. Thank you for changing it for consistency for now.

**Review by projectavi — APPROVED** [review]

**Review by sal3h-yas1in — APPROVED** [review]
We should get to testing the database integration at our earliest convenience, so we can be done with this portion of our project
Everything looks smooth so far, good job :)

**Review by kunzhi-yu — APPROVED** [review]
Excellent use of data structures to effectively retrieve and save data into the group. Moreover, despite not worked on group data, I can easily understand your code.

**Pull request merged**
