### PR TITLE
small changes in group create and group join test cases

### LINKED ISSUE #3: [Feature 3] Group join, group create use cases
Allow a user to create new group.
Allow a user to join a group.

Implement all the associated input output boundaries

### PR DESCRIPTION
**Pull request by mishaalkandapath**

### CODE REVIEW

**Review by sal3h-yas1in — APPROVED** [review]
While I notice the inclusion of more IF statements to further refine the code, I would appreciate some documentation/comments to explain what is being done at a current point in this file. That would help a reader understand the code more

**Comment by projectavi** [comment]
Commenting but not approving, looks good though

**Review by rowanArora — APPROVED** [review]
This looks great! Adding tests to check if user IDs and group IDs exist is perfect! Even though I can understand what your tests are checking for, I would like to see more comments documenting these tests. I do not know if this would be necessary for your test case, but maybe adding a test which checks to see if the user is in the group after your use case has been called would be useful.
Thank you so much for your work!

**Review by rcordi — APPROVED** [review]
Thank you for fixing errors in the test cases.

**Pull request merged**
