### PR TITLE
AddPurchase Implementation

### LINKED ISSUE #5: [Feature 5] AddPurchase Use Case
Updates item by adding split with who and purchase cost
Then, adds this item to PurchaseList
Calls RemoveFromPlanning to remove the item from the planning list
Passes the cost and split with who to UpdatePaymentBalance

Implement all the necessary input/output boundaries.

### PR DESCRIPTION
**Pull request by projectavi**
Completed the use case and controller for the addpurchase use case. Implemented the input and output boundaries. Added a framework for the presenter to be updated later when the view is completed. Added placeholder function names for data access functions that have not yet been implemented or defined. Revamped the data structures to only use primitive data types instead of entities.

### CODE REVIEW

**Review by kunzhi-yu — CHANGES_REQUESTED** [review]
executeUseCase is smelly it has bloaters. You should break the code into a few helper methods. You did the presenters and boundaries as well.

**Review by kunzhi-yu — CHANGES_REQUESTED** [review]
To add users to a list of participating users, you should use a helper method. https://sourcemaking.com/refactoring/smells/long-method . This website has more treatments for your executeUseCase method.

**Review by kunzhi-yu — APPROVED** [review]
Thanks for taking the time to make this code less smelly, Its a lot easier to understand now.

**Review by sal3h-yas1in — APPROVED** [review]
I am glad you adhered to the principles of clean architecture and good code design. I would suggest utilizing more comments to help someone else reviewing the code, but it was nothing complex so I understood it all the same. Good work :)

**Review by sopleee — APPROVED** [review]
thanks for removing unused imports, it makes the code cleaner and easier to read. the helper functions prevent the code from bloating. your use case follows clean architecture, so looks good to me

**Pull request merged**
