### PR TITLE
Fixed bugs in addpurchase use case and implemented tests for addpurchase use case

### LINKED ISSUE #5: [Feature 5] AddPurchase Use Case
Updates item by adding split with who and purchase cost
Then, adds this item to PurchaseList
Calls RemoveFromPlanning to remove the item from the planning list
Passes the cost and split with who to UpdatePaymentBalance

Implement all the necessary input/output boundaries.

### PR DESCRIPTION
**Pull request by projectavi**

### CODE REVIEW

**Review by mishaalkandapath — CHANGES_REQUESTED** [review]
Thank you for making the changes due to Entity chaining being ID based, and for implementing iteration through entities.
Please resolve the merge conflicts

**Review by mishaalkandapath — APPROVED** [review]
Thanks for resolving the conflicts!

**Review by kunzhi-yu — APPROVED** [review]
Good testing procedure. Thanks for updating addpurchase in accordance with new data structure.

**Review by sal3h-yas1in — APPROVED** [review]
I parsed through your tests and I think these tests cover all sorts of situations, including edge cases!

**Review by sopleee — CHANGES_REQUESTED** [review]
thanks for adjusting your use case to use the iterator design pattern and use userids, and groupids. 
these tests' data access instances should include "test" as an argument- this will activate data recovery based on the testing database

**Review by sopleee — APPROVED** [review]
thanks for updating test data access and moving your files

**Pull request merged**
