### PR TITLE
implemented full settlement payment user flow and data collection

### LINKED ISSUE #38: [Feature 10] Settlement Payment Use Case

### PR DESCRIPTION
**Pull request by sopleee**
Completed: SettlementPayment use case, controller, presenter, input boundary, output boundary, input and output data structures implementations. 

Data outputted for the view: a String outcome message containing potential errors, purchase balance as a list of list of strings

Things to do next: write javadocs for all the code, write tests which tests all methods of the use case file

### CODE REVIEW

**Review by kunzhi-yu — APPROVED** [review]
Nice javadocs. Good implementation of SettlementPayment. Also consider breaking executeDebtSettlement into a few helper methods.

**Review by projectavi — APPROVED** [review]
Good javadocs and overall documentation. Everything seems good with your code upon reading. Approving the pull request.

**Comment by mishaalkandapath** [comment]
Javadocs have been modified to tailor to this specific use case.
the error raising repeateed lines were extracted into a new method.

Please review again, thanks

**Review by rcordi — APPROVED** [review]
Detailed documentation and javadocs. Good implementation of Debt controller and Updated Debts.

**Pull request merged**
