### PR TITLE
added semicolon so that the program would compile

### LINKED ISSUE #3: [Feature 3] Group join, group create use cases
Allow a user to create new group.
Allow a user to join a group.

Implement all the associated input output boundaries

### PR DESCRIPTION
**Pull request by sopleee**

### CODE REVIEW

**Review by projectavi — APPROVED** [review]
lol nice

**Review by mishaalkandapath — CHANGES_REQUESTED** [review]
please check for code compilation before merging pull requests (can merge if the errors are not for this branch). Thank you for fixing the semi colon.

Please fix the paths to the database files.

**Review by kunzhi-yu — APPROVED** [review]
Good. We can avoid these issues in the future by reviewing Intellj warnings before PR.

**Review by mishaalkandapath — APPROVED** [review]
Correct changes to the file paths now. Thanks!

**Pull request merged**
